name: one_flutter

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    run: flutter pub global run melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.
  unit_test:
    run: flutter pub global run melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run all Flutter tests in this project.
